development:
  adapter: mysql2
  encoding: utf8
  database: swarm-dev
  pool: 5
  username: swarm
  password: swarm
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: swarm-test
  pool: 5
  username: swarm
  password: swarm
  socket: /tmp/mysql.sock
    
production:
  adapter: mysql2
  encoding: utf8
  database: swarm
  pool: 5
  username: root
  password: admin
  socket: /var/run/mysqld/mysqld.sock